Alias /cbmrn/ /var/www/cbmrn/public/
Alias /cbmrn /var/www/cbmrn/public/

<Directory /var/www/cbmrn/public>
    Options -Indexes +FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

RewriteEngine On
RewriteRule ^/cbmrn$ /cbmrn/ [R=301,L]

SetEnvIf Request_URI "^/cbmrn(/|$)" app_cbmrn
