SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE dog_handlers;
TRUNCATE TABLE dog_health_records;
TRUNCATE TABLE dog_evaluations;
TRUNCATE TABLE dog_missions;
TRUNCATE TABLE dog_vaccinations;
TRUNCATE TABLE dogs;
TRUNCATE TABLE dog_breeds;
TRUNCATE TABLE gallery_images;
TRUNCATE TABLE gallery_categories;
TRUNCATE TABLE livro_ocorrencias;
TRUNCATE TABLE livro_ocorrencia_tipos;
TRUNCATE TABLE posts;
TRUNCATE TABLE pessoal;
TRUNCATE TABLE equipamentos;
TRUNCATE TABLE obras;
TRUNCATE TABLE funcoes;
TRUNCATE TABLE categorias_equipamentos;
TRUNCATE TABLE categorias_posts;
TRUNCATE TABLE municipios_ibge;
TRUNCATE TABLE users;

SET FOREIGN_KEY_CHECKS = 1;

-- Baseline completo do portal, incluindo municípios e ocorrências para alimentar a seção "Mapa operacional".

-- Usuários base
INSERT INTO users (username, email, password, role, status, ativo, ultimo_login)
VALUES
('admin',    'admin@example.com',    '$2y$12$R.6qwqUnKUam4PutfWdvTOvD6iWVIWv/O6biYFIpRG8wDms.hC8ju', 'admin',   'ativo',    1, NOW()),
('gerente',  'gerente@example.com',  '$2y$12$R.6qwqUnKUam4PutfWdvTOvD6iWVIWv/O6biYFIpRG8wDms.hC8ju', 'gerente', 'ativo',    1, NOW()),
('operador', 'operador@example.com', '$2y$12$R.6qwqUnKUam4PutfWdvTOvD6iWVIWv/O6biYFIpRG8wDms.hC8ju', 'operador','ativo',    1, NOW()),
('reporter', 'reporter@example.com', '$2y$12$R.6qwqUnKUam4PutfWdvTOvD6iWVIWv/O6biYFIpRG8wDms.hC8ju', 'usuario', 'pendente', 0, NULL);

-- Categorias de posts
INSERT INTO categorias_posts (staff_id, nome, slug, descricao, badge_color, icone) VALUES
('CATPOST-202501010001', 'Operações',     'operacoes',                'Atualizações operacionais e relatórios oficiais.', '#df6301', 'bi-flag'),
('CATPOST-202501010002', 'Treinamentos',  'treinamentos',             'Capacitações internas e certificações.',          '#006989', 'bi-mortarboard'),
('CATPOST-202501010003', 'Cobertura',     'cobertura',                'Cobertura de eventos e ações de campo.',          '#198754', 'bi-broadcast-pin'),
('CATPOST-202501010004', 'Transparência', 'transparencia',            'Prestação de contas e relatórios públicos.',      '#6f42c1', 'bi-journal-richtext'),
('CATPOST-202501010005', 'Cursos CBMRN', 'cursos-cbmrn', 'Programas formativos conduzidos pelo CBMRN.', '#0d6efd', 'bi-building'),
('CATPOST-202501010006', 'Estágios CBMRN', 'estagios-cbmrn', 'Vagas e relatos de estágios oferecidos pelo CBMRN.', '#6610f2', 'bi-briefcase'),
('CATPOST-202501010007', 'Capacitação CBMRN', 'capacitacao-cbmrn', 'Planejamento de capacitações e reciclagens internas.', '#20c997', 'bi-lightning-charge'),
('CATPOST-202501010008', 'Integração com outros CBM', 'integracao-outros-cbm', 'Cursos, estágios e missões em outros corpos de bombeiros.', '#fd7e14', 'bi-people'),
('CATPOST-202501010009', 'Curso de Socorrista', 'curso-de-socorrista', 'Informes específicos sobre formações de primeiros socorros.', '#ff6b6b', 'bi-heart-pulse'),
('CATPOST-202501010010', 'Datas comemorativas', 'datas-comemorativas', 'Homenagens e lembranças de datas oficiais.', '#e83e8c', 'bi-calendar-event'),
('CATPOST-202501010011', 'Torneio de cães de combate', 'torneio-caes-combate', 'Cobertura esportiva e técnica dos torneios K9.', '#ffb703', 'bi-trophy'),
('CATPOST-202501010012', 'Institucional', 'institucional', 'Comunicados e posicionamentos institucionais.', '#495057', 'bi-building-lock'),
('CATPOST-202501010013', 'Legislação', 'legislacao', 'Normativos, decretos e atualizações legais.', '#1982c4', 'bi-file-earmark-text'),
('CATPOST-202501010014', 'Outros', 'outros', 'Publicações diversas fora das categorias principais.', '#adb5bd', 'bi-three-dots'),
('CATPOST-202501010015', 'Informação', 'informacao', 'Notas rápidas e informativos ao público.', '#0abde3', 'bi-info-circle'),
('CATPOST-202501010016', 'Adestramento', 'adestramento', 'Conteúdo focado em treinamento de cães operacionais.', '#f77f00', 'bi-badge-cc'),
('CATPOST-202501010017', 'Missão conjunta', 'missao-conjunta', 'Relatos de missões com outras forças.', '#8d99ae', 'bi-people-fill'),
('CATPOST-202501010018', 'Campanhas de prevenção', 'campanhas-prevencao', 'Ações educativas e campanhas ao público.', '#2ec4b6', 'bi-megaphone'),
('CATPOST-202501010019', 'Vistorias', 'vistorias', 'Fiscalizações e inspeções técnicas.', '#212529', 'bi-clipboard-check'),
('CATPOST-202501010020', 'Busca e salvamento', 'busca-e-salvamento', 'Operações de busca terrestre, aquática ou aérea.', '#6a994e', 'bi-life-preserver'),
('CATPOST-202501010021', 'Resgate', 'resgate', 'Ocorrências de resgate técnico e emergencial.', '#c1121f', 'bi-activity');

-- Municípios IBGE (2º SGB RN)
INSERT INTO municipios_ibge (codigo, nome, uf, uf_nome, regiao) VALUES
(2404200, 'Goianinha', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2402204, 'Canguaretama', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2401404, 'Baía Formosa', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2414209, 'Tibau do Sul', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2413201, 'Senador Georgino Avelino', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2408201, 'Nísia Floresta', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2412203, 'São José de Mipibu', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2407807, 'Monte Alegre', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2414803, 'Vera Cruz', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2406601, 'Lagoa Salgada', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2406304, 'Lagoa de Pedras', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2401800, 'Brejinho', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2409209, 'Passagem', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2403509, 'Espírito Santo', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2414704, 'Várzea', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2406155, 'Jundiá', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2409803, 'Pedro Velho', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2415008, 'Vila Flor', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2408300, 'Nova Cruz', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2411502, 'Santo Antônio', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2413508, 'Serrinha', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2406205, 'Lagoa d''Anta', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2401701, 'Bom Jesus', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2401206, 'Arês', 'RN', 'Rio Grande do Norte', 'Nordeste'),
(2403251, 'Parnamirim', 'RN', 'Rio Grande do Norte', 'Nordeste');

-- Categorias de equipamentos
INSERT INTO categorias_equipamentos (staff_id, nome) VALUES
('CATEQP-202501010001', 'Ferramentas Manuais'),
('CATEQP-202501010002', 'Equipamentos de Proteção Individual'),
('CATEQP-202501010003', 'Veículos e Resgate');

-- Funções
INSERT INTO funcoes (staff_id, nome) VALUES
('FUNC-202501010001', 'Comandante geral'),
('FUNC-202501010002', 'Sucomandante operacional'),
('FUNC-202501010003', 'Subcomandante administrativo'),
('FUNC-202501010004', 'Chefe de Gabinete'),
('FUNC-202501010005', 'Chefe do Estado-Maior'),
('FUNC-202501010006', 'Chefe do Setor de Planejamento Operacional'),
('FUNC-202501010007', 'Chefe do setor de Logística'),
('FUNC-202501010008', 'Chefe do setor de Pessoal'),
('FUNC-202501010009', 'Chefe do setor de Finanças'),
('FUNC-202501010010', 'Oficial de Operações'),
('FUNC-202501010011', 'Oficial de Serviço'),
('FUNC-202501010012', 'Inspetor de Material e Patrimônio'),
('FUNC-202501010013', 'Analista de Sistemas'),
('FUNC-202501010014', 'Analista Administrativo'),
('FUNC-202501010015', 'Analista Financeiro'),
('FUNC-202501010016', 'Analista de Recursos Humanos'),
('FUNC-202501010017', 'Analista de Logística'),
('FUNC-202501010018', 'Analista de Comunicação Social'),
('FUNC-202501010019', 'Analista de Planejamento'),
('FUNC-202501010020', 'Técnico em Segurança do Trabalho'),
('FUNC-202501010021', 'Técnico em Logística'),
('FUNC-202501010022', 'Técnico em Administração'),
('FUNC-202501010023', 'Técnico em Informática'),
('FUNC-202501010024', 'Assistente Administrativo'),
('FUNC-202501010025', 'Assistente de Recursos Humanos'),
('FUNC-202501010026', 'Assistente de Comunicação Social'),
('FUNC-202501010027', 'Assistente Financeiro'),
('FUNC-202501010028', 'Assistente de Logística'),
('FUNC-202501010029', 'Motorista Operacional'),
('FUNC-202501010030', 'Operador de Máquinas Pesadas'),
('FUNC-202501010031', 'Auxiliar de Serviços Gerais'),
('FUNC-202501010032', 'Recepcionista'),
('FUNC-202501010033', 'Telefonista'),
('FUNC-202501010034', 'Agente de Segurança Patrimonial'),
('FUNC-202501010035', 'Comandante de Grupamento'),
('FUNC-202501010036', 'Subcomandante de Grupamento'),
('FUNC-202501010037', 'Chefe de Seção'),
('FUNC-202501010038', 'Chefe de Equipe'),
('FUNC-202501010039', 'Bombeiro Militar Especialista'),
('FUNC-202501010040', 'Bombeiro Militar Generalista'),
('FUNC-202501010041', 'Condutor de Veículo de Emergência'),
('FUNC-202501010042', 'Técnico em Emergências Médicas'),
('FUNC-202501010043', 'Mergulhador de Resgate'),
('FUNC-202501010044', 'Piloto de Aeronave'),
('FUNC-202501010045', 'Atendente de Emergências'),
('FUNC-202501010046', 'Instrutor de Treinamento'),
('FUNC-202501010047', 'Analista de Prevenção e Combate a Incêndios'),
('FUNC-202501010048', 'Analista de Busca e Resgate'),
('FUNC-202501010049', 'Analista de Defesa Civil'),
('FUNC-202501010050', 'Analista de Proteção Ambiental'),
('FUNC-202501010051', 'Analista de Comunicação em Emergências'),
('FUNC-202501010052', 'Analista de Logística em Emergências'),
('FUNC-202501010053', 'Bombeiro Civil'),
('FUNC-202501010054', 'Bombeiro Militar'),
('FUNC-202501010055', 'Soldado Bombeiro Militar'),
('FUNC-202501010056', 'Estagiário'),
('FUNC-202501010057', 'Analista de Inteligência'),
('FUNC-202501010058', 'Condutor(a) de Cães de Busca e Resgate');

-- Obras
INSERT INTO obras (
    numero_obra, natureza_obra, descricao, endereco, cep,
    data_inicio, data_termino, status, prioridade, valor_estimado, observacoes
) VALUES
('OBRA-2025-001', 'Reforma de Quartel', 'Requalificação estrutural do 2º SGB/2º GBM.', 'Av. Prudente de Morais, 2410 - Natal/RN', '59064-620', '2025-01-02', NULL, 'Em Andamento', 'Alta', 450000.00, 'Projeto financiado via convênio estadual.'),
('OBRA-2025-002', 'Centro de Treinamento', 'Nova torre de treinamento para operações em altura.', 'BR-101, Km 153 - Parnamirim/RN', '59148-000', '2024-09-15', NULL, 'Planejamento', 'Média', 275000.00, 'Projeto aguardando licitação.');

-- Equipamentos
INSERT INTO equipamentos (
    staff_id, nome, codigo, serial_number, descricao, marca, modelo, data_fabricacao, estado, quantidade_estoque, categoria_id
) VALUES
('EQP-202501010001', 'Kit Desencarcerador', 'EQP-001', 'SN-45821', 'Conjunto hidráulico para resgate veicular.', 'Holmatro', 'Serie X', '2023-06-15', 'Operacional', 2, 3),
('EQP-202501010002', 'Capacete Estrutural Gallet', 'EQP-002', 'SN-99811', 'Capacete com viseira e proteção auricular.', 'MSA', 'F1XF', '2024-03-20', 'Operacional', 20, 2),
('EQP-202501010003', 'Detector Multigás', 'EQP-003', 'SN-77421', 'Monitoramento de ambientes confinados.', 'Dräger', 'X-am 5600', '2022-11-02', 'Manutenção', 4, 1);

-- Pessoal
INSERT INTO pessoal (
    staff_id, nome, cpf, nascimento, telefone, foto, funcao_id, obra_id, data_admissao, status, jornada, observacoes
) VALUES
('FIREMAN-202501010001', 'Samuel Lira Tavares',   '12345678901', '1987-04-10', '84999990000', NULL, 1, NULL, '2010-05-12', 'Ativo',    '24x72', 'Responsável pelo planejamento operacional.'),
('FIREMAN-202501010002', 'Karen de lima Góes',    '98765432100', '1990-09-22', '84988889999', NULL, 2, 1,    '2014-08-03', 'Ativo',    '24x72', 'Coordena equipes em campo.'),
('FIREMAN-202501010003', 'Bruno Ferreira',  '11122233344', '1985-01-18', '84977776666', NULL, 3, NULL, '2008-02-17', 'Férias',   '24x72', 'Instrutor chefe de resgate veicular.'),
('FIREMAN-202501010004', 'Ana Vasconcelos',  '55566677788', '1994-12-05', '84966665555', NULL, 4, 2,    '2018-10-10', 'Afastado', '12x36', 'Analista de dados operacionais.');

-- Posts de exemplo
INSERT INTO posts (
    user_id, titulo, slug, conteudo, capa_url, categoria_id, status, reject_reason, is_hidden, published_at
) VALUES
(1, 'Missão permanente do 2º SGB', 'missao-permanente-2sgb', '<h1>Planejamento estratégico em campo</h1><p>O 2º Subgrupamento de Bombeiros Militar mantém equipes 24/7 distribuídas entre litoral e agreste, garantindo resposta coordenada para incêndios, salvamentos e apoio de Defesa Civil. A missão combina disciplina operacional, inteligência territorial e proximidade com as prefeituras parceiras.</p>', NULL, 1, 'published', NULL, 0, '2025-01-05 08:00:00'),
(2, 'Desafios logísticos na faixa litorânea', 'desafios-logisticos-litoral', '<h1>Rotas e recursos críticos</h1><p>As viaturas operacionais do 2º Subgrupamento de Bombeiros Militar atuam em um território marcado por diversidade geográfica e desafios logísticos, deslocando-se por rodovias estaduais, acessos vicinais e áreas de dunas para garantir o atendimento às comunidades pesqueiras e demais localidades sob sua responsabilidade. Cada guarnição opera com o apoio de checklists digitais e sistemas de monitoramento, permitindo o acompanhamento em tempo real das condições das viaturas, do abastecimento, da disponibilidade de equipamentos e dos tempos de despacho, assegurando maior eficiência, rastreabilidade e prontidão operacional.</p>', NULL, 2, 'published', NULL, 0, '2025-01-08 09:30:00'),
(3, 'Profissionalização do efetivo', 'profissionalizacao-efetivo', '<h1>Treinamento contínuo</h1><p>Instrutores especializados em salvamento em altura, mergulho e atendimento pré-hospitalar conduzem módulos periódicos de capacitação, estruturados a partir de cenários reais e recorrentes do litoral sul potiguar. Os conteúdos contemplam desde a análise de riscos geográficos e ambientais até a aplicação de protocolos operacionais e de comunicação integrada com o Serviço de Atendimento Móvel de Urgência (SAMU) e a Polícia Militar, fortalecendo a interoperabilidade e a prontidão das equipes.</p>', NULL, 3, 'published', NULL, 0, NULL),
(4, 'Integração com defesas civis municipais', 'integracao-defesa-civil', '<h1>Gabinetes integrados</h1><p>Reuniões periódicas de caráter estratégico consolidam a análise de dados meteorológicos, o histórico de ocorrências e as demandas sociais da região atendida. A partir desses encontros, o 2º Subgrupamento de Bombeiros Militar coordena a elaboração e a atualização de planos de contingência, além de manter canais permanentes de articulação com as secretarias municipais, visando agilizar a ativação de abrigos temporários e o desenvolvimento de ações educativas e preventivas junto à população.</p>', NULL, 4, 'published', NULL, 0, NULL),
(2, 'Programa de estágio operacional', 'programa-estagio-operacional', '<h1>Imersão supervisionada</h1><p>Estagiários acompanham guarnições em vistorias técnicas, simulados e oficinas de manutenção. Cada ciclo termina com avaliação sobre postura, domínio dos EPIs e entendimento das rotinas administrativas do Subgrupamento.</p>', NULL, 1, 'published', NULL, 0, NULL),
(1, 'Rotinas de salvamento aquático', 'rotinas-salvamento-aquatico', '<h1>Monitoramento das marés</h1><p>As equipes de salvamento do 2º Subgrupamento de Bombeiros Militar realizam o mapeamento sistemático de marés, correntes marítimas e pontos críticos de risco à navegação, especialmente para embarcações de pequeno porte e atividades costeiras. O planejamento operacional contempla a disponibilidade permanente de kits de primeiros socorros, pranchas de resgate e sistemas de comunicação redundantes, integrando rádio operacional e aplicativos institucionais, de modo a assegurar coordenação eficiente, resposta rápida e segurança nas operações de salvamento aquático.</p>', NULL, 3, 'published', NULL, 0, '2025-02-10 10:45:00'),
(3, 'Uso de tecnologia no mapa operacional', 'tecnologia-mapa-operacional', '<h1>Dados para tomada de decisão</h1><p>O painel interativo reúne ocorrências por município, tipo e status, permitindo gestão mais precisa de recursos. Alertas de alta demanda são compartilhados com o comando para reposicionar guarnições e reforçar plantões noturnos.</p>', NULL, 2, 'published', NULL, 0, NULL),
(4, 'Gestão de pessoas em turnos extensos', 'gestao-pessoas-turnos', '<h1>Cuidado com o efetivo</h1><p>Psicólogos e assistentes sociais acompanham militares que atuam em ocorrências críticas. Quando necessário, escalas são ajustadas e são oferecidas sessões de descompressão para mitigar fadiga operacional.</p>', NULL, 4, 'published', NULL, 0, NULL),
(1, 'Atuação em eventos de grande público', 'atuacao-eventos-grande-publico', '<h1>Planos especiais</h1><p>Eventos de grande porte, como carnavais, festivais religiosos e corridas de aventura, são atendidos mediante a elaboração de planos operacionais específicos, desenvolvidos de forma integrada entre o 2º Subgrupamento de Bombeiros Militar, o Serviço de Atendimento Móvel de Urgência (SAMU) e a Polícia Militar. Esses planejamentos definem corredores de evacuação, pontos de triagem e atendimento, além de canais exclusivos de comunicação por meio de rádio digital, assegurando coordenação, agilidade e segurança durante a realização dos eventos.</p>', NULL, 2, 'published', NULL, 0, '2025-03-01 14:20:00'),
(2, 'Cultura de prevenção em escolas', 'cultura-prevencao-escolas', '<h1>Educação para risco</h1><p>Militares ministram oficinas sobre evacuação, primeiros socorros e uso responsável de gás GLP. As visitas incluem demonstrações com extintores e orientação para criação de brigadas escolares.</p>', NULL, 3, 'published', NULL, 0, NULL),
(3, 'Planejamento para estiagens prolongadas', 'planejamento-estiagens', '<h1>Riscos hidrológicos</h1><p>O Subgrupamento mantém inventário de açudes e áreas de vegetação suscetíveis a queimadas. Durante estiagens, são executadas campanhas de conscientização e posicionadas unidades de apoio em municípios críticos.</p>', NULL, 1, 'published', NULL, 0, NULL),
(4, 'Resposta rápida a acidentes rodoviários', 'resposta-rapida-rodovias', '<h1>Coordenação multiagência</h1><p>As ocorrências registradas ao longo da BR-101 exigem atuação coordenada e alinhamento operacional entre o 2º Subgrupamento de Bombeiros Militar, a Polícia Rodoviária Federal e as concessionárias responsáveis pelo trecho. Nessas situações, o 2º SGB emprega equipamentos especializados, como desencarceradores portáteis, além do uso de drones para reconhecimento e avaliação inicial do cenário, permitindo maior segurança na intervenção e subsidiando o acesso das equipes médicas de forma eficiente e controlada.</p>', NULL, 2, 'published', NULL, 0, '2025-03-15 09:00:00'),
(2, 'Inovação na gestão documental', 'inovacao-gestao-documental', '<h1>Livro digital atualizado</h1><p>Os registros de ocorrências agora são alimentados diretamente via tablets nas viaturas. Com isso, indicadores operacionais ficam disponíveis em segundos e alimentam relatórios de desempenho para o comando regional.</p>', NULL, 4, 'published', NULL, 0, NULL),
(1, 'Mapa operacional aproxima comunidade e guarnições', 'mapa-operacional-ocorrencias-municipio', '<h1>Visão territorial em tempo real</h1><p>O novo mapa operacional <strong>“Ocorrências por Município”</strong>, disponível na página inicial, consolida informações estratégicas ao integrar os registros do livro digital de ocorrências às frentes de serviço ativas do 2º Subgrupamento de Bombeiros Militar. A ferramenta permite visualizar, em tempo quase real, o volume e a distribuição dos atendimentos realizados em cada município sob responsabilidade da unidade.</p><h2>Apoio à gestão e à tomada de decisão</h2><p>Ao oferecer uma leitura territorial imediata das demandas operacionais, o painel subsidia o reposicionamento de viaturas, o dimensionamento do efetivo e o reforço de recursos materiais conforme a dinâmica das ocorrências. Além disso, a visualização dos dados facilita a articulação institucional com prefeitos, secretarias municipais e lideranças locais, que passam a dispor de indicadores confiáveis e transparentes para o planejamento de ações preventivas e respostas coordenadas.</p><h2>Transparência e fortalecimento do vínculo com a comunidade</h2><p>Para a população, a ferramenta amplia a previsibilidade e o acesso à informação. Os moradores podem identificar períodos de maior incidência de ocorrências, adotar medidas de autoproteção e acompanhar a atuação do Corpo de Bombeiros com base em dados oficiais. Esse processo contribui para o fortalecimento da confiança institucional, estimulando a participação social e o diálogo qualificado entre a comunidade e o 2º Subgrupamento de Bombeiros Militar.</p>', NULL, 1, 'published', NULL, 0, '2025-03-20 07:30:00');

-- Categorias da galeria
INSERT INTO gallery_categories (nome, slug, color) VALUES
('Operações aquáticas', 'operacoes-aquaticas', '#ff0000'),
('Adestramento', 'adestramento', '#df6301'),
('Busca e resgate', 'busca-e-resgate', '#ffffff'),
('Formaturas', 'formaturas', '#269717'),
('Cursos CBMRN', 'cursos-cbmrn', '#28d7ba'),
('Torneios', 'torneios', '#df01cd'),
('Estágios CBMRN', 'estagios-cbmrn', '#749400'),
('Combate a incêndios urbanos e florestais', 'combate-a-incendios', '#db1a1a'),
('Resgate veicular', 'resgate-veicular', '#86df01'),
('Salvamento aquático em áreas alagadas', 'salvamento-aquatico', '#01dcdf'),
('Cooperação com outras FS', 'cooperacao', '#df01af'),
('Cursos de formação e especialização', 'curso-formacao', '#201e1e'),
('Atividades administrativas técnicas', 'atividades-administrativas', '#0109df'),
('Campanhas de prevenção', 'campanhas-prevencao', '#df6301'),
('Entrega de medalhas e condecorações', 'medalhas-condecoracoes', '#cac1b9'),
('Datas comemorativas', 'datas', '#69635d'),
('Vistorias técnicas', 'vistorias', '#dd9e6e');

-- Imagens da galeria (K9)
INSERT INTO gallery_images (category_id, titulo, descricao, url, data_upload) VALUES
(2, 'Circuito de obediência integrada', 'Binômios treinam comandos de precisão com foco em controle de faro.', 'https://plus.unsplash.com/premium_photo-1669277336130-f5efae4b4d60?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', '2025-01-05 08:10:00'),
(3, 'Simulado urbano de busca', 'Equipe K9 varre corredores estreitos para localizar vítimas sinalizadas.', 'https://images.unsplash.com/photo-1554956615-1ba6dc39921b?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', '2025-01-07 09:20:00'),
(10, 'Reconhecimento em píer alagado', 'Cão operacional se adapta à plataforma molhada antes de embarcar.', 'https://images.unsplash.com/photo-1558788353-f76d92427f16?q=80&w=738&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', '2025-01-09 07:45:00'),
(8, 'Briefing com guarnição de incêndio', 'Mascote tático acompanha dupla que testará equipamentos térmicos.', 'https://images.unsplash.com/photo-1554235386-82e08c80c3ef?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', '2025-01-11 18:30:00'),
(9, 'Inspeção em cenário veicular', 'Faro direcionado para detecção de fluidos e ocupantes presos.', 'https://images.unsplash.com/photo-1477973770766-6228305816df?auto=format&fit=crop&w=1600&h=1067&q=80', '2025-01-13 10:15:00'),
(7, 'Estágio integrado com novos condutores', 'Instrutores apresentam protocolos de segurança para o turno de estágio.', 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?q=80&w=694&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', '2025-01-15 16:20:00'),
(5, 'Oficina de atendimento pré-hospitalar', 'Alunos praticam contenção de vítimas com o apoio dos cães certificados.', 'https://images.unsplash.com/photo-1444212477490-ca407925329e?auto=format&fit=crop&w=1600&h=1067&q=80', '2025-01-17 08:50:00'),
(11, 'Operação conjunta com Polícia Rodoviária', 'Briefing alinhou sinais de comunicação entre forças estaduais.', 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=1600&h=1067&q=80', '2025-01-19 06:40:00'),
(1, 'Patrulha costeira com bote inflável', 'Equipe testa equilíbrio antes do embarque para varredura litorânea.', 'https://images.unsplash.com/photo-1543606818-2e9bf5e642f3?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', '2025-01-21 07:05:00'),
(14, 'Campanha “Adote atitudes seguras”', 'K9 auxilia em ação educativa para comunidades ribeirinhas.', 'https://plus.unsplash.com/premium_photo-1663127271882-e1be1f18f153?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', '2025-01-23 09:55:00'),
(12, 'Módulo de planejamento de missões', 'Instrutores avaliam checklists digitais ao lado dos binômios.', 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?auto=format&fit=crop&w=1600&h=1067&q=80', '2025-01-25 11:25:00'),
(4, 'Formatura da turma K9/2025', 'Cerimônia reconhece condutores e cães certificados no trimestre.', 'https://images.unsplash.com/photo-1525253086316-d0c936c814f8?auto=format&fit=crop&w=1600&h=1067&q=80', '2025-01-27 19:10:00'),
(16, 'Celebração do Dia Nacional do Bombeiro', 'Demonstração pública reuniu famílias e equipes operacionais.', 'https://images.unsplash.com/photo-1656191166912-297d52280911?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', '2025-07-02 10:00:00'),
(15, 'Entrega de medalha Mérito K9', 'Cão Hera recebe honraria por apoio em missão de longa duração.', 'https://images.unsplash.com/photo-1523626797181-8c5ae80d40c2?auto=format&fit=crop&w=1600&h=1067&q=80', '2025-02-01 17:45:00'),
(13, 'Planejamento administrativo do canil', 'Time revisa matrizes de risco e cronogramas de manutenção.', 'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?auto=format&fit=crop&w=1600&h=1067&q=80', '2025-02-03 15:00:00'),
(6, 'Torneio interno de agilidade', 'Prova cronometrada avalia confiança em obstáculos elevados.', 'https://images.unsplash.com/photo-1575785662490-1e3ce6806ed5?q=80&w=1956&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', '2025-02-05 08:30:00'),
(3, 'Simulado em estruturas colapsadas', 'Dupla percorre área demarcada com sensores acústicos.', 'https://images.unsplash.com/photo-1564585531329-8c74d6cc02b5?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', '2025-02-07 09:40:00'),
(2, 'Treino de obediência com clicker', 'Instrutores reforçam comandos básicos para novos filhotes.', 'https://plus.unsplash.com/premium_photo-1718055459856-37136a5f7203?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', '2025-02-09 07:25:00'),
(10, 'Embarque para resgate em área alagada', 'Binômio assegura ancoragem antes de seguir para comunidade isolada.', 'https://images.unsplash.com/photo-1453487977089-77350a275ec5?q=80&w=1173&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', '2025-02-11 06:55:00'),
(11, 'Operação com agentes ambientais', 'Equipe conjunta com órgãos ambientais monitora área de preservação.', 'https://images.unsplash.com/photo-1558788353-f76d92427f16?q=80&w=738&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', '2025-02-13 12:15:00');

INSERT INTO dog_breeds (name, slug, size, `function`, origin, description, image_url)
VALUES
('Pastor Alemão', 'pastor-alemao', 'large', 'working', 'Alemanha', 'Raça versátil para busca, guarda e detecção.', 'https://placedog.net/256/256?id=1'),
('Labrador Retriever', 'labrador-retriever', 'large', 'sporting', 'Canadá', 'Companheiro sociável com foco em apoio aquático.', 'https://placedog.net/256/256?id=2'),
('Belgian Malinois', 'belgian-malinois', 'medium', 'working', 'Bélgica', 'Obediência e agilidade ideais para missões táticas.', 'https://placedog.net/256/256?id=3'),
('Bloodhound', 'bloodhound', 'large', 'hunting', 'Reino Unido', 'Especialista em rastros extensos em terreno difícil.', 'https://placedog.net/256/256?id=4'),
('Jack Russell Terrier', 'jack-russell-terrier', 'small', 'terrier', 'Inglaterra', 'Terrier compacto e curioso para inspeções rápidas.', 'https://placedog.net/256/256?id=5'),
('Golden Retriever', 'golden-retriever', 'large', 'sporting', 'Escócia', 'Equilíbrio entre docilidade e disposição para busca.', 'https://placedog.net/256/256?id=6'),
('Doberman Pinscher', 'doberman-pinscher', 'large', 'guard', 'Alemanha', 'Sentinela atlético com forte instinto protetor.', 'https://placedog.net/256/256?id=7'),
('Rottweiler', 'rottweiler', 'large', 'guard', 'Alemanha', 'Força e estabilidade para guarda de perímetro.', 'https://placedog.net/256/256?id=8'),
('German Shorthaired Pointer', 'german-shorthaired-pointer', 'medium', 'sporting', 'Alemanha', 'Versátil em apontamento e recolha em campo aberto.', 'https://placedog.net/256/256?id=9'),
('English Springer Spaniel', 'english-springer-spaniel', 'medium', 'sporting', 'Inglaterra', 'Spaniel atento para busca em ambientes densos.', 'https://placedog.net/256/256?id=10'),
('Border Collie', 'border-collie', 'medium', 'herding', 'Reino Unido', 'Capacidade de pastoreio precisa e responsiva.', 'https://placedog.net/256/256?id=11'),
('Dutch Shepherd', 'dutch-shepherd', 'medium', 'herding', 'Países Baixos', 'Pastoreio polivalente com alta resistência.', 'https://placedog.net/256/256?id=12'),
('Giant Schnauzer', 'giant-schnauzer', 'large', 'working', 'Alemanha', 'Robusto e alerta para guarda de instalações.', 'https://placedog.net/256/256?id=13'),
('Saint Bernard', 'saint-bernard', 'giant', 'working', 'Suíça', 'Histórico em buscas alpinas e apoio humanitário.', 'https://placedog.net/256/256?id=14'),
('Newfoundland', 'newfoundland', 'giant', 'working', 'Canadá', 'Nadador potente indicado para salvamento aquático.', 'https://placedog.net/256/256?id=15'),
('Akita Inu', 'akita-inu', 'large', 'guard', 'Japão', 'Sentinela silencioso com grande lealdade.', 'https://placedog.net/256/256?id=16'),
('Alaskan Malamute', 'alaskan-malamute', 'giant', 'working', 'Estados Unidos', 'Tracionador de carga com excelente resistência ao frio.', 'https://placedog.net/256/256?id=17'),
('Siberian Husky', 'siberian-husky', 'medium', 'working', 'Rússia', 'Equipe de trenó leve e veloz para terrenos nevados.', 'https://placedog.net/256/256?id=18'),
('Australian Shepherd', 'australian-shepherd', 'medium', 'herding', 'Estados Unidos', 'Gestor ágil de rebanhos com grande inteligência.', 'https://placedog.net/256/256?id=19'),
('Boxer', 'boxer', 'large', 'guard', 'Alemanha', 'Combina guarda com alta energia operacional.', 'https://placedog.net/256/256?id=20'),
('Cane Corso', 'cane-corso', 'large', 'guard', 'Itália', 'Molosso firme e equilibrado para proteção patrimonial.', 'https://placedog.net/256/256?id=21'),
('Dogo Argentino', 'dogo-argentino', 'large', 'guard', 'Argentina', 'Ativo em patrulhas rurais e operações táticas.', 'https://placedog.net/256/256?id=22'),
('American Pit Bull Terrier', 'american-pit-bull-terrier', 'medium', 'guard', 'Estados Unidos', 'Musculoso e determinado com alto limiar de dor.', 'https://placedog.net/256/256?id=23'),
('American Staffordshire Terrier', 'american-staffordshire-terrier', 'medium', 'guard', 'Estados Unidos', 'Companheiro vigilante para missões urbanas.', 'https://placedog.net/256/256?id=24'),
('Vizsla', 'vizsla', 'medium', 'sporting', 'Hungria', 'Atirador ágil para apontamento em campo aberto.', 'https://placedog.net/256/256?id=25'),
('Weimaraner', 'weimaraner', 'large', 'sporting', 'Alemanha', 'Cão de caça veloz com olfato refinado.', 'https://placedog.net/256/256?id=26'),
('English Pointer', 'english-pointer', 'medium', 'hunting', 'Inglaterra', 'Apontador clássico para terrenos planos.', 'https://placedog.net/256/256?id=27'),
('Basset Hound', 'basset-hound', 'medium', 'hunting', 'França', 'Baixo e resiliente para rastros lentos.', 'https://placedog.net/256/256?id=28'),
('Beagle', 'beagle', 'small', 'hunting', 'Inglaterra', 'Grande faro para inspeções alfandegárias.', 'https://placedog.net/256/256?id=29'),
('Cocker Spaniel', 'cocker-spaniel', 'small', 'sporting', 'Inglaterra', 'Spaniel compacto para ambientes fechados.', 'https://placedog.net/256/256?id=30'),
('English Setter', 'english-setter', 'large', 'sporting', 'Inglaterra', 'Setter elegante para apoio em caça de pluma.', 'https://placedog.net/256/256?id=31'),
('Irish Setter', 'irish-setter', 'large', 'sporting', 'Irlanda', 'Perna longa com foco em coberturas extensas.', 'https://placedog.net/256/256?id=32'),
('Gordon Setter', 'gordon-setter', 'large', 'sporting', 'Escócia', 'Setter robusto para clima frio e úmido.', 'https://placedog.net/256/256?id=33'),
('Flat-Coated Retriever', 'flat-coated-retriever', 'large', 'sporting', 'Inglaterra', 'Retriever versátil com entusiasmo constante.', 'https://placedog.net/256/256?id=34'),
('Chesapeake Bay Retriever', 'chesapeake-bay-retriever', 'large', 'sporting', 'Estados Unidos', 'Especialista em águas frias e resgate aquático.', 'https://placedog.net/256/256?id=35'),
('Kuvasz', 'kuvasz', 'large', 'guard', 'Hungria', 'Protetor tradicional de rebanhos com postura independente.', 'https://placedog.net/256/256?id=36'),
('Komondor', 'komondor', 'large', 'guard', 'Hungria', 'Pelagem em cordas que camufla entre ovelhas.', 'https://placedog.net/256/256?id=37'),
('Great Pyrenees', 'great-pyrenees', 'giant', 'guard', 'França', 'Guardião sereno para pastoreio em montanhas.', 'https://placedog.net/256/256?id=38'),
('Bernese Mountain Dog', 'bernese-mountain-dog', 'large', 'working', 'Suíça', 'Trabalho em fazendas e apoio emocional.', 'https://placedog.net/256/256?id=39'),
('Leonberger', 'leonberger', 'giant', 'working', 'Alemanha', 'Gigante gentil adequado a missões de tração leve.', 'https://placedog.net/256/256?id=40'),
('Anatolian Shepherd', 'anatolian-shepherd', 'giant', 'guard', 'Turquia', 'Defensor resistente usado em áreas rurais.', 'https://placedog.net/256/256?id=41'),
('Kangal', 'kangal', 'giant', 'guard', 'Turquia', 'Proteção de rebanhos com mordida poderosa.', 'https://placedog.net/256/256?id=42'),
('Presa Canario', 'presa-canario', 'large', 'guard', 'Espanha', 'Molosso firme para guarda perimetral.', 'https://placedog.net/256/256?id=43'),
('Rhodesian Ridgeback', 'rhodesian-ridgeback', 'large', 'hunting', 'Zimbábue', 'Corredor estável para terrenos quentes.', 'https://placedog.net/256/256?id=44'),
('Saluki', 'saluki', 'medium', 'hunting', 'Oriente Médio', 'Galgo do deserto com grande resistência.', 'https://placedog.net/256/256?id=45'),
('Pharaoh Hound', 'pharaoh-hound', 'medium', 'hunting', 'Malta', 'Linha leve para perseguições rápidas.', 'https://placedog.net/256/256?id=46'),
('Whippet', 'whippet', 'medium', 'sporting', 'Inglaterra', 'Sprinter silencioso para provas curtas.', 'https://placedog.net/256/256?id=47'),
('Greyhound', 'greyhound', 'large', 'sporting', 'Inglaterra', 'Velocista clássico para rastreamento visual.', 'https://placedog.net/256/256?id=48'),
('Italian Greyhound', 'italian-greyhound', 'small', 'toy', 'Itália', 'Mini galgo para companhia leve.', 'https://placedog.net/256/256?id=49'),
('Portuguese Water Dog', 'portuguese-water-dog', 'medium', 'sporting', 'Portugal', 'Nadador nato para apoio em embarcações.', 'https://placedog.net/256/256?id=50'),
('Spanish Water Dog', 'spanish-water-dog', 'medium', 'sporting', 'Espanha', 'Pelagem encaracolada para missões anfíbias.', 'https://placedog.net/256/256?id=51'),
('Lagotto Romagnolo', 'lagotto-romagnolo', 'small', 'sporting', 'Itália', 'Especialista em detecção de trufas e odores finos.', 'https://placedog.net/256/256?id=52'),
('Poodle Standard', 'poodle-standard', 'large', 'sporting', 'Alemanha', 'Inteligente e apto a resgates aquáticos.', 'https://placedog.net/256/256?id=53'),
('Poodle Miniature', 'poodle-miniature', 'small', 'non-sporting', 'França', 'Companheiro alerta para ambientes urbanos.', 'https://placedog.net/256/256?id=54'),
('Poodle Toy', 'poodle-toy', 'small', 'toy', 'França', 'Miniatura leve para suporte emocional.', 'https://placedog.net/256/256?id=55'),
('Miniature Schnauzer', 'miniature-schnauzer', 'small', 'terrier', 'Alemanha', 'Terrier vigilante com baixa queda de pelo.', 'https://placedog.net/256/256?id=56'),
('Standard Schnauzer', 'standard-schnauzer', 'medium', 'working', 'Alemanha', 'Guarda familiar equilibrado e atlético.', 'https://placedog.net/256/256?id=57'),
('Scottish Terrier', 'scottish-terrier', 'small', 'terrier', 'Escócia', 'Perfil destemido para inspeções em túneis.', 'https://placedog.net/256/256?id=58'),
('Airedale Terrier', 'airedale-terrier', 'medium', 'terrier', 'Inglaterra', 'Maior dos terriers, ótimo em patrulhas mistas.', 'https://placedog.net/256/256?id=59'),
('Bull Terrier', 'bull-terrier', 'medium', 'terrier', 'Inglaterra', 'Cabeça única e muita disposição física.', 'https://placedog.net/256/256?id=60'),
('Cairn Terrier', 'cairn-terrier', 'small', 'terrier', 'Escócia', 'Terrier de tocas para ambientes rochosos.', 'https://placedog.net/256/256?id=61'),
('West Highland White Terrier', 'west-highland-white-terrier', 'small', 'terrier', 'Escócia', 'Alvo e alerta em inspeções domiciliares.', 'https://placedog.net/256/256?id=62'),
('Smooth Fox Terrier', 'smooth-fox-terrier', 'small', 'terrier', 'Inglaterra', 'Rápido para desentocar presas pequenas.', 'https://placedog.net/256/256?id=63'),
('Australian Cattle Dog', 'australian-cattle-dog', 'medium', 'herding', 'Austrália', 'Condutor incansável adaptado a calor extremo.', 'https://placedog.net/256/256?id=64'),
('Belgian Tervuren', 'belgian-tervuren', 'medium', 'herding', 'Bélgica', 'Variedade elegante focada em obediência.', 'https://placedog.net/256/256?id=65'),
('Belgian Laekenois', 'belgian-laekenois', 'medium', 'herding', 'Bélgica', 'Pelagem áspera para proteção climática.', 'https://placedog.net/256/256?id=66'),
('Collie Rough', 'collie-rough', 'large', 'herding', 'Escócia', 'Pastoreio tradicional com longa pelagem.', 'https://placedog.net/256/256?id=67'),
('Collie Smooth', 'collie-smooth', 'large', 'herding', 'Escócia', 'Versão curta com mesma aptidão de comando.', 'https://placedog.net/256/256?id=68'),
('Shetland Sheepdog', 'shetland-sheepdog', 'small', 'herding', 'Escócia', 'Mini collie eficiente em espaços reduzidos.', 'https://placedog.net/256/256?id=69'),
('Old English Sheepdog', 'old-english-sheepdog', 'large', 'herding', 'Inglaterra', 'Pelagem dupla para climas frios e úmidos.', 'https://placedog.net/256/256?id=70'),
('Briard', 'briard', 'large', 'herding', 'França', 'Pastoreio noturno graças à audição apurada.', 'https://placedog.net/256/256?id=71'),
('Bouvier des Flandres', 'bouvier-des-flandres', 'large', 'herding', 'Bélgica', 'Combina tração, guarda e condução de rebanhos.', 'https://placedog.net/256/256?id=72'),
('Puli', 'puli', 'medium', 'herding', 'Hungria', 'Cordas naturais que protegem contra intempéries.', 'https://placedog.net/256/256?id=73'),
('Pumi', 'pumi', 'small', 'herding', 'Hungria', 'Mistura de terrier e pastor altamente sonora.', 'https://placedog.net/256/256?id=74'),
('Swedish Vallhund', 'swedish-vallhund', 'small', 'herding', 'Suécia', 'Baixo e robusto para manobras com gado.', 'https://placedog.net/256/256?id=75'),
('Norwegian Elkhound', 'norwegian-elkhound', 'medium', 'hunting', 'Noruega', 'Caçador de alces com resistência ao frio.', 'https://placedog.net/256/256?id=76'),
('Finnish Spitz', 'finnish-spitz', 'small', 'hunting', 'Finlândia', 'Ponta a caça com latido característico.', 'https://placedog.net/256/256?id=77'),
('Basenji', 'basenji', 'small', 'hunting', 'Congo', 'Cão que não late, útil em missões furtivas.', 'https://placedog.net/256/256?id=78'),
('Shiba Inu', 'shiba-inu', 'small', 'companion', 'Japão', 'Compacto e vigilante para ambientes urbanos.', 'https://placedog.net/256/256?id=79'),
('Kishu Ken', 'kishu-ken', 'medium', 'hunting', 'Japão', 'Caçador de javalis com grande foco.', 'https://placedog.net/256/256?id=80'),
('Kai Ken', 'kai-ken', 'medium', 'hunting', 'Japão', 'Raro e escalador nato em terrenos montanhosos.', 'https://placedog.net/256/256?id=81'),
('Thai Ridgeback', 'thai-ridgeback', 'medium', 'guard', 'Tailândia', 'Linha dorsal em destaque e ótimo salto.', 'https://placedog.net/256/256?id=82'),
('Chinese Shar-Pei', 'chinese-shar-pei', 'medium', 'guard', 'China', 'Pele enrugada que protege em confrontos.', 'https://placedog.net/256/256?id=83'),
('Chow Chow', 'chow-chow', 'medium', 'guard', 'China', 'Sentinela independente com língua azul.', 'https://placedog.net/256/256?id=84'),
('Samoyed', 'samoyed', 'medium', 'working', 'Rússia', 'Pelagem branca para tração em clima ártico.', 'https://placedog.net/256/256?id=85'),
('American Eskimo Dog', 'american-eskimo-dog', 'small', 'companion', 'Estados Unidos', 'Spitz branco para truques e apresentações.', 'https://placedog.net/256/256?id=86'),
('Great Dane', 'great-dane', 'giant', 'guard', 'Alemanha', 'Gigante gentil utilizado em dissuasão visual.', 'https://placedog.net/256/256?id=87'),
('Irish Wolfhound', 'irish-wolfhound', 'giant', 'hunting', 'Irlanda', 'Altura extrema para enfrentar lobos.', 'https://placedog.net/256/256?id=88'),
('Scottish Deerhound', 'scottish-deerhound', 'giant', 'hunting', 'Escócia', 'Especialista em cervos em campo aberto.', 'https://placedog.net/256/256?id=89'),
('Borzoi', 'borzoi', 'large', 'hunting', 'Rússia', 'Galgo aristocrático para perseguições rápidas.', 'https://placedog.net/256/256?id=90'),
('Azawakh', 'azawakh', 'medium', 'hunting', 'Sahel', 'Levíssimo para patrulhas no deserto.', 'https://placedog.net/256/256?id=91'),
('Xoloitzcuintli', 'xoloitzcuintli', 'medium', 'companion', 'México', 'Cão sem pelo com uso terapêutico tradicional.', 'https://placedog.net/256/256?id=92'),
('Peruvian Inca Orchid', 'peruvian-inca-orchid', 'medium', 'companion', 'Peru', 'Variedade sem pelo adaptada a climas secos.', 'https://placedog.net/256/256?id=93'),
('Afghan Hound', 'afghan-hound', 'large', 'hunting', 'Afeganistão', 'Pelagem longa ideal para frio montanhoso.', 'https://placedog.net/256/256?id=94'),
('English Mastiff', 'english-mastiff', 'giant', 'guard', 'Inglaterra', 'Molosso pesado para guarda dissuasiva.', 'https://placedog.net/256/256?id=95'),
('Bullmastiff', 'bullmastiff', 'giant', 'guard', 'Inglaterra', 'Mistura de bulldog com mastim para patrulhas noturnas.', 'https://placedog.net/256/256?id=96'),
('Neapolitan Mastiff', 'neapolitan-mastiff', 'giant', 'guard', 'Itália', 'Dobras protegem em confrontos diretos.', 'https://placedog.net/256/256?id=97'),
('Tibetan Mastiff', 'tibetan-mastiff', 'giant', 'guard', 'China', 'Guardião ancestral de mosteiros e vilas.', 'https://placedog.net/256/256?id=98'),
('Maremma Sheepdog', 'maremma-sheepdog', 'large', 'guard', 'Itália', 'Protetor branco que trabalha solto com o rebanho.', 'https://placedog.net/256/256?id=99'),
('Spanish Mastiff', 'spanish-mastiff', 'giant', 'guard', 'Espanha', 'Acompanha transumância defendendo gado.', 'https://placedog.net/256/256?id=100');

-- Cães K9 (sementes)
INSERT INTO dogs (
    name, slug, breed_id, birth_date, birth_city, birth_state, weight_kg,
    sex, operational_function, training_phase, avatar, status, notes, identifying_marks
)
VALUES
('Thor', 'thor-k9', 1, '2020-05-10', 'Natal', 'RN', 34.50, 'male', 'search_rescue', 'iib', 'https://placedog.net/256/256?id=201', 'available', 'Binômio destacado para operações costeiras e buscas urbanas.', 'Cicatriz discreta na orelha esquerda'),
('Ayla', 'ayla-k9', 2, '2019-11-22', 'Parnamirim', 'RN', 28.20, 'female', 'scent', 'i3', 'https://placedog.net/256/256?id=202', 'training', 'Excelente faro aquático, em fase de aperfeiçoamento para missões com embarcações.', 'Pelagem mais clara no peito'),
('Koda', 'koda-k9', 3, '2018-03-15', 'Recife', 'PE', 30.10, 'male', 'guard', 'iiq', 'https://placedog.net/256/256?id=203', 'inactive', 'Em processo de readaptação física após pequena lesão muscular.', 'Mancha escura próxima ao olho direito'),
('Nala', 'nala-k9', 4, '2021-02-08', 'João Pessoa', 'PB', 25.40, 'female', 'scent', 'iib', 'https://placedog.net/256/256?id=204', 'available', 'Especialista em rastros de longa duração em vegetação densa.', 'Marca branca em formato de meia na pata dianteira'),
('Ragnar', 'ragnar-k9', 5, '2017-07-19', 'Curitiba', 'PR', 38.10, 'male', 'guard', 'iiq', 'https://placedog.net/256/256?id=205', 'inactive', 'Designado para vigilância de depósitos estratégicos.', 'Orelha direita levemente dobrada'),
('Maya', 'maya-k9', 6, '2020-09-30', 'Campinas', 'SP', 27.80, 'female', 'search_rescue', 'i3', 'https://placedog.net/256/256?id=206', 'training', 'Em formação para busca em soterramentos urbanos.', 'Pelagem dourada mais escura na cauda'),
('Apollo', 'apollo-k9', 7, '2019-05-12', 'Fortaleza', 'CE', 32.60, 'male', 'guard', 'iib', 'https://placedog.net/256/256?id=207', 'available', 'Responsável por rondas noturnas em aeroportos.', 'Duas manchas escuras simétricas no peito'),
('Gaia', 'gaia-k9', 8, '2018-12-03', 'Maceió', 'AL', 29.10, 'female', 'search_rescue', 'iib', 'https://placedog.net/256/256?id=208', 'available', 'Atua em deslizamentos com alta tolerância a ruídos.', 'Pelagem predominantemente preta com focinho claro'),
('Zeus', 'zeus-k9', 9, '2017-04-21', 'Vitória', 'ES', 31.90, 'male', 'scent', 'iiq', 'https://placedog.net/256/256?id=209', 'inactive', 'Reservado para instrução de novos condutores.', 'Tufos claros acima dos olhos'),
('Luna', 'luna-k9', 10, '2021-06-18', 'Belém', 'PA', 24.30, 'female', 'scent', 'i3', 'https://placedog.net/256/256?id=210', 'training', 'Foco em detecção de substâncias incendiárias.', 'Linha branca contínua da testa ao focinho'),
('Orion', 'orion-k9', 11, '2018-01-25', 'Londrina', 'PR', 26.70, 'male', 'other', 'iib', 'https://placedog.net/256/256?id=211', 'available', 'Alocado para apoio em manejo de animais durante evacuações.', 'Ponta da cauda levemente torta'),
('Kira', 'kira-k9', 12, '2020-03-14', 'Florianópolis', 'SC', 23.90, 'female', 'search_rescue', 'iib', 'https://placedog.net/256/256?id=212', 'available', 'Ótimo desempenho em áreas litorâneas com vento forte.', 'Máscara escura envolvendo os olhos'),
('Atlas', 'atlas-k9', 13, '2017-10-05', 'Santa Maria', 'RS', 40.20, 'male', 'guard', 'iiq', 'https://placedog.net/256/256?id=213', 'available', 'Suporte em operações de guarda de comboios.', 'Cicatriz longitudinal no dorso'),
('Mel', 'mel-k9', 14, '2019-08-27', 'Uberlândia', 'MG', 36.40, 'female', 'search_rescue', 'i3', 'https://placedog.net/256/256?id=214', 'available', 'Histórico em missões de resfriamento de vítimas.', 'Pelagem castanho-avermelhada uniforme'),
('Bolt', 'bolt-k9', 15, '2021-01-09', 'Manaus', 'AM', 28.90, 'male', 'other', 'iib', 'https://placedog.net/256/256?id=215', 'training', 'Programa piloto de logística com drones.', 'Pequena mecha branca no topo da cabeça'),
('Freya', 'freya-k9', 16, '2018-11-11', 'Porto Alegre', 'RS', 33.50, 'female', 'guard', 'iiq', 'https://placedog.net/256/256?id=216', 'available', 'Atua em comboios oficiais de altas autoridades.', 'Olhos castanhos com halo âmbar'),
('Logan', 'logan-k9', 17, '2019-02-04', 'Aracaju', 'SE', 35.70, 'male', 'search_rescue', 'iib', 'https://placedog.net/256/256?id=217', 'available', 'Especialista em buscas noturnas com baixa luminosidade.', 'Listra cinza sobre o lombo'),
('Stella', 'stella-k9', 18, '2020-10-23', 'São Luís', 'MA', 26.10, 'female', 'scent', 'i3', 'https://placedog.net/256/256?id=218', 'training', 'Treinada para detecção de acelerantes químicos.', 'Orelhas pontudas com extremidades claras'),
('Ghost', 'ghost-k9', 19, '2018-05-29', 'Foz do Iguaçu', 'PR', 31.40, 'male', 'guard', 'iiq', 'https://placedog.net/256/256?id=219', 'available', 'Opera em bases fronteiriças de alta vigilância.', 'Pelagem cinza quase branca, olhos azuis'),
('Zara', 'zara-k9', 20, '2021-04-01', 'Rio Branco', 'AC', 22.80, 'female', 'search_rescue', 'iib', 'https://placedog.net/256/256?id=220', 'available', 'Equipe de pronta resposta para enchentes amazônicas.', 'Pequena mancha em formato de estrela no peito');

-- Tipos de ocorrências do livro
INSERT INTO livro_ocorrencia_tipos (nome, slug, descricao, badge_color, ativo) VALUES
('Busca e Salvamento', 'busca-e-salvamento', 'Resgates terrestres, aquáticos e buscas especializadas por desaparecidos.', '#f97316', 1),
('Resgate Marítimo', 'resgate-maritimo', 'Operações embarcadas e ocorrências em faixa costeira ou mar aberto.', '#0284c7', 1),
('Incêndio Estrutural', 'incendio-estrutural', 'Atendimentos em edificações residenciais, comerciais e industriais.', '#dc2626', 1),
('Incêndio Florestal', 'incendio-florestal', 'Combate a queimadas e monitoramento de áreas de vegetação.', '#ea580c', 1),
('Defesa Civil', 'defesa-civil', 'Ações preventivas e resposta a desastres em articulação com defesas civis municipais.', '#6366f1', 1),
('Suporte Pré-Hospitalar', 'suporte-pre-hospitalar', 'Estabilização de vítimas e atendimento médico inicial.', '#10b981', 1),
('Outros', 'outros', 'Registros que não se enquadram nas tipologias principais ou operações experimentais.', '#6b7280', 1);

-- Livro de ocorrências (2º SGB - 2025)
INSERT INTO livro_ocorrencias (
    protocolo, data_ocorrencia, municipio_codigo, municipio_nome, subgrupamento,
    tipo_id, descricao, relatorio_conclusao, status, responsavel_id
) VALUES
    ('OCR-20250103-0001', '2025-01-03 08:15:00', 2404200, 'Goianinha/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'busca-e-salvamento'), '<p>Atendimento de busca e salvamento em Goianinha, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250106-0002', '2025-01-06 08:50:00', 2402204, 'Canguaretama/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'resgate-maritimo'), '<p>Atendimento de resgate marítimo em Canguaretama, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250109-0003', '2025-01-09 09:25:00', 2401404, 'Baía Formosa/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-estrutural'), '<p>Atendimento de incêndio estrutural em Baía Formosa, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250112-0004', '2025-01-12 10:00:00', 2414209, 'Tibau do Sul/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-florestal'), '<p>Atendimento de incêndio florestal em Tibau do Sul, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250115-0005', '2025-01-15 10:35:00', 2413201, 'Senador Georgino Avelino/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'defesa-civil'), '<p>Atendimento de defesa civil em Senador Georgino Avelino, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250118-0006', '2025-01-18 11:10:00', 2408201, 'Nísia Floresta/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'suporte-pre-hospitalar'), '<p>Atendimento de suporte pré-hospitalar em Nísia Floresta, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250121-0007', '2025-01-21 08:15:00', 2412203, 'São José de Mipibu/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'outros'), '<p>Atendimento de outros em São José de Mipibu, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250124-0008', '2025-01-24 08:50:00', 2407807, 'Monte Alegre/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'busca-e-salvamento'), '<p>Atendimento de busca e salvamento em Monte Alegre, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250127-0009', '2025-01-27 09:25:00', 2414803, 'Vera Cruz/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'resgate-maritimo'), '<p>Atendimento de resgate marítimo em Vera Cruz, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250130-0010', '2025-01-30 10:00:00', 2406601, 'Lagoa Salgada/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-estrutural'), '<p>Atendimento de incêndio estrutural em Lagoa Salgada, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250202-0011', '2025-02-02 10:35:00', 2406304, 'Lagoa de Pedras/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-florestal'), '<p>Atendimento de incêndio florestal em Lagoa de Pedras, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250205-0012', '2025-02-05 11:10:00', 2401800, 'Brejinho/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'defesa-civil'), '<p>Atendimento de defesa civil em Brejinho, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250209-0013', '2025-02-09 08:15:00', 2409209, 'Passagem/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'suporte-pre-hospitalar'), '<p>Atendimento de suporte pré-hospitalar em Passagem, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250212-0014', '2025-02-12 08:50:00', 2403509, 'Espírito Santo/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'outros'), '<p>Atendimento de outros em Espírito Santo, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250215-0015', '2025-02-15 09:25:00', 2414704, 'Várzea/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'busca-e-salvamento'), '<p>Atendimento de busca e salvamento em Várzea, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250218-0016', '2025-02-18 10:00:00', 2406155, 'Jundiá/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'resgate-maritimo'), '<p>Atendimento de resgate marítimo em Jundiá, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250221-0017', '2025-02-21 10:35:00', 2409803, 'Pedro Velho/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-estrutural'), '<p>Atendimento de incêndio estrutural em Pedro Velho, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250224-0018', '2025-02-24 11:10:00', 2415008, 'Vila Flor/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-florestal'), '<p>Atendimento de incêndio florestal em Vila Flor, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250227-0019', '2025-02-27 08:15:00', 2408300, 'Nova Cruz/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'defesa-civil'), '<p>Atendimento de defesa civil em Nova Cruz, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250302-0020', '2025-03-02 08:50:00', 2411502, 'Santo Antônio/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'suporte-pre-hospitalar'), '<p>Atendimento de suporte pré-hospitalar em Santo Antônio, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250305-0021', '2025-03-05 09:25:00', 2413508, 'Serrinha/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'outros'), '<p>Atendimento de outros em Serrinha, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250308-0022', '2025-03-08 10:00:00', 2406205, 'Lagoa d''Anta/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'busca-e-salvamento'), '<p>Atendimento de busca e salvamento em Lagoa d''Anta, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250311-0023', '2025-03-11 10:35:00', 2401701, 'Bom Jesus/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'resgate-maritimo'), '<p>Atendimento de resgate marítimo em Bom Jesus, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250314-0024', '2025-03-14 11:10:00', 2401206, 'Arês/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-estrutural'), '<p>Atendimento de incêndio estrutural em Arês, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250318-0025', '2025-03-18 08:15:00', 2403251, 'Parnamirim/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-florestal'), '<p>Atendimento de incêndio florestal em Parnamirim, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250321-0026', '2025-03-21 08:50:00', 2404200, 'Goianinha/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'defesa-civil'), '<p>Atendimento de defesa civil em Goianinha, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250324-0027', '2025-03-24 09:25:00', 2402204, 'Canguaretama/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'suporte-pre-hospitalar'), '<p>Atendimento de suporte pré-hospitalar em Canguaretama, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250327-0028', '2025-03-27 10:00:00', 2401404, 'Baía Formosa/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'outros'), '<p>Atendimento de outros em Baía Formosa, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250330-0029', '2025-03-30 10:35:00', 2414209, 'Tibau do Sul/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'busca-e-salvamento'), '<p>Atendimento de busca e salvamento em Tibau do Sul, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250402-0030', '2025-04-02 11:10:00', 2413201, 'Senador Georgino Avelino/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'resgate-maritimo'), '<p>Atendimento de resgate marítimo em Senador Georgino Avelino, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250405-0031', '2025-04-05 08:15:00', 2408201, 'Nísia Floresta/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-estrutural'), '<p>Atendimento de incêndio estrutural em Nísia Floresta, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250408-0032', '2025-04-08 08:50:00', 2412203, 'São José de Mipibu/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-florestal'), '<p>Atendimento de incêndio florestal em São José de Mipibu, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250411-0033', '2025-04-11 09:25:00', 2407807, 'Monte Alegre/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'defesa-civil'), '<p>Atendimento de defesa civil em Monte Alegre, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250414-0034', '2025-04-14 10:00:00', 2414803, 'Vera Cruz/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'suporte-pre-hospitalar'), '<p>Atendimento de suporte pré-hospitalar em Vera Cruz, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250417-0035', '2025-04-17 10:35:00', 2406601, 'Lagoa Salgada/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'outros'), '<p>Atendimento de outros em Lagoa Salgada, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250420-0036', '2025-04-20 11:10:00', 2406304, 'Lagoa de Pedras/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'busca-e-salvamento'), '<p>Atendimento de busca e salvamento em Lagoa de Pedras, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250424-0037', '2025-04-24 08:15:00', 2401800, 'Brejinho/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'resgate-maritimo'), '<p>Atendimento de resgate marítimo em Brejinho, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250427-0038', '2025-04-27 08:50:00', 2409209, 'Passagem/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-estrutural'), '<p>Atendimento de incêndio estrutural em Passagem, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250430-0039', '2025-04-30 09:25:00', 2403509, 'Espírito Santo/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-florestal'), '<p>Atendimento de incêndio florestal em Espírito Santo, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250503-0040', '2025-05-03 10:00:00', 2414704, 'Várzea/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'defesa-civil'), '<p>Atendimento de defesa civil em Várzea, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250506-0041', '2025-05-06 10:35:00', 2406155, 'Jundiá/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'suporte-pre-hospitalar'), '<p>Atendimento de suporte pré-hospitalar em Jundiá, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250509-0042', '2025-05-09 11:10:00', 2409803, 'Pedro Velho/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'outros'), '<p>Atendimento de outros em Pedro Velho, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250512-0043', '2025-05-12 08:15:00', 2415008, 'Vila Flor/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'busca-e-salvamento'), '<p>Atendimento de busca e salvamento em Vila Flor, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250515-0044', '2025-05-15 08:50:00', 2408300, 'Nova Cruz/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'resgate-maritimo'), '<p>Atendimento de resgate marítimo em Nova Cruz, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250518-0045', '2025-05-18 09:25:00', 2411502, 'Santo Antônio/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-estrutural'), '<p>Atendimento de incêndio estrutural em Santo Antônio, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250521-0046', '2025-05-21 10:00:00', 2413508, 'Serrinha/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-florestal'), '<p>Atendimento de incêndio florestal em Serrinha, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250524-0047', '2025-05-24 10:35:00', 2406205, 'Lagoa d''Anta/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'defesa-civil'), '<p>Atendimento de defesa civil em Lagoa d''Anta, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250527-0048', '2025-05-27 11:10:00', 2401701, 'Bom Jesus/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'suporte-pre-hospitalar'), '<p>Atendimento de suporte pré-hospitalar em Bom Jesus, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250531-0049', '2025-05-31 08:15:00', 2401206, 'Arês/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'outros'), '<p>Atendimento de outros em Arês, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250603-0050', '2025-06-03 08:50:00', 2403251, 'Parnamirim/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'busca-e-salvamento'), '<p>Atendimento de busca e salvamento em Parnamirim, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250606-0051', '2025-06-06 09:25:00', 2404200, 'Goianinha/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'resgate-maritimo'), '<p>Atendimento de resgate marítimo em Goianinha, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250609-0052', '2025-06-09 10:00:00', 2402204, 'Canguaretama/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-estrutural'), '<p>Atendimento de incêndio estrutural em Canguaretama, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250612-0053', '2025-06-12 10:35:00', 2401404, 'Baía Formosa/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-florestal'), '<p>Atendimento de incêndio florestal em Baía Formosa, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250615-0054', '2025-06-15 11:10:00', 2414209, 'Tibau do Sul/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'defesa-civil'), '<p>Atendimento de defesa civil em Tibau do Sul, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250618-0055', '2025-06-18 08:15:00', 2413201, 'Senador Georgino Avelino/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'suporte-pre-hospitalar'), '<p>Atendimento de suporte pré-hospitalar em Senador Georgino Avelino, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250621-0056', '2025-06-21 08:50:00', 2408201, 'Nísia Floresta/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'outros'), '<p>Atendimento de outros em Nísia Floresta, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250624-0057', '2025-06-24 09:25:00', 2412203, 'São José de Mipibu/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'busca-e-salvamento'), '<p>Atendimento de busca e salvamento em São José de Mipibu, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250627-0058', '2025-06-27 10:00:00', 2407807, 'Monte Alegre/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'resgate-maritimo'), '<p>Atendimento de resgate marítimo em Monte Alegre, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250630-0059', '2025-06-30 10:35:00', 2414803, 'Vera Cruz/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-estrutural'), '<p>Atendimento de incêndio estrutural em Vera Cruz, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250703-0060', '2025-07-03 11:10:00', 2406601, 'Lagoa Salgada/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-florestal'), '<p>Atendimento de incêndio florestal em Lagoa Salgada, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250707-0061', '2025-07-07 08:15:00', 2406304, 'Lagoa de Pedras/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'defesa-civil'), '<p>Atendimento de defesa civil em Lagoa de Pedras, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250710-0062', '2025-07-10 08:50:00', 2401800, 'Brejinho/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'suporte-pre-hospitalar'), '<p>Atendimento de suporte pré-hospitalar em Brejinho, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250713-0063', '2025-07-13 09:25:00', 2409209, 'Passagem/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'outros'), '<p>Atendimento de outros em Passagem, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250716-0064', '2025-07-16 10:00:00', 2403509, 'Espírito Santo/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'busca-e-salvamento'), '<p>Atendimento de busca e salvamento em Espírito Santo, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250719-0065', '2025-07-19 10:35:00', 2414704, 'Várzea/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'resgate-maritimo'), '<p>Atendimento de resgate marítimo em Várzea, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250722-0066', '2025-07-22 11:10:00', 2406155, 'Jundiá/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-estrutural'), '<p>Atendimento de incêndio estrutural em Jundiá, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250725-0067', '2025-07-25 08:15:00', 2409803, 'Pedro Velho/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-florestal'), '<p>Atendimento de incêndio florestal em Pedro Velho, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250728-0068', '2025-07-28 08:50:00', 2415008, 'Vila Flor/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'defesa-civil'), '<p>Atendimento de defesa civil em Vila Flor, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250731-0069', '2025-07-31 09:25:00', 2408300, 'Nova Cruz/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'suporte-pre-hospitalar'), '<p>Atendimento de suporte pré-hospitalar em Nova Cruz, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250803-0070', '2025-08-03 10:00:00', 2411502, 'Santo Antônio/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'outros'), '<p>Atendimento de outros em Santo Antônio, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250806-0071', '2025-08-06 10:35:00', 2413508, 'Serrinha/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'busca-e-salvamento'), '<p>Atendimento de busca e salvamento em Serrinha, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250809-0072', '2025-08-09 11:10:00', 2406205, 'Lagoa d''Anta/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'resgate-maritimo'), '<p>Atendimento de resgate marítimo em Lagoa d''Anta, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250813-0073', '2025-08-13 08:15:00', 2401701, 'Bom Jesus/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-estrutural'), '<p>Atendimento de incêndio estrutural em Bom Jesus, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250816-0074', '2025-08-16 08:50:00', 2401206, 'Arês/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-florestal'), '<p>Atendimento de incêndio florestal em Arês, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250819-0075', '2025-08-19 09:25:00', 2403251, 'Parnamirim/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'defesa-civil'), '<p>Atendimento de defesa civil em Parnamirim, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250822-0076', '2025-08-22 10:00:00', 2404200, 'Goianinha/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'suporte-pre-hospitalar'), '<p>Atendimento de suporte pré-hospitalar em Goianinha, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250825-0077', '2025-08-25 10:35:00', 2402204, 'Canguaretama/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'outros'), '<p>Atendimento de outros em Canguaretama, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250828-0078', '2025-08-28 11:10:00', 2401404, 'Baía Formosa/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'busca-e-salvamento'), '<p>Atendimento de busca e salvamento em Baía Formosa, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250831-0079', '2025-08-31 08:15:00', 2414209, 'Tibau do Sul/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'resgate-maritimo'), '<p>Atendimento de resgate marítimo em Tibau do Sul, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250903-0080', '2025-09-03 08:50:00', 2413201, 'Senador Georgino Avelino/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-estrutural'), '<p>Atendimento de incêndio estrutural em Senador Georgino Avelino, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250906-0081', '2025-09-06 09:25:00', 2408201, 'Nísia Floresta/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-florestal'), '<p>Atendimento de incêndio florestal em Nísia Floresta, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250909-0082', '2025-09-09 10:00:00', 2412203, 'São José de Mipibu/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'defesa-civil'), '<p>Atendimento de defesa civil em São José de Mipibu, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250912-0083', '2025-09-12 10:35:00', 2407807, 'Monte Alegre/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'suporte-pre-hospitalar'), '<p>Atendimento de suporte pré-hospitalar em Monte Alegre, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250915-0084', '2025-09-15 11:10:00', 2414803, 'Vera Cruz/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'outros'), '<p>Atendimento de outros em Vera Cruz, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20250919-0085', '2025-09-19 08:15:00', 2406601, 'Lagoa Salgada/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'busca-e-salvamento'), '<p>Atendimento de busca e salvamento em Lagoa Salgada, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20250922-0086', '2025-09-22 08:50:00', 2406304, 'Lagoa de Pedras/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'resgate-maritimo'), '<p>Atendimento de resgate marítimo em Lagoa de Pedras, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20250925-0087', '2025-09-25 09:25:00', 2401800, 'Brejinho/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-estrutural'), '<p>Atendimento de incêndio estrutural em Brejinho, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20250928-0088', '2025-09-28 10:00:00', 2409209, 'Passagem/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-florestal'), '<p>Atendimento de incêndio florestal em Passagem, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20251001-0089', '2025-10-01 10:35:00', 2403509, 'Espírito Santo/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'defesa-civil'), '<p>Atendimento de defesa civil em Espírito Santo, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20251004-0090', '2025-10-04 11:10:00', 2414704, 'Várzea/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'suporte-pre-hospitalar'), '<p>Atendimento de suporte pré-hospitalar em Várzea, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20251007-0091', '2025-10-07 08:15:00', 2406155, 'Jundiá/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'outros'), '<p>Atendimento de outros em Jundiá, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20251010-0092', '2025-10-10 08:50:00', 2409803, 'Pedro Velho/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'busca-e-salvamento'), '<p>Atendimento de busca e salvamento em Pedro Velho, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20251013-0093', '2025-10-13 09:25:00', 2415008, 'Vila Flor/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'resgate-maritimo'), '<p>Atendimento de resgate marítimo em Vila Flor, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20251016-0094', '2025-10-16 10:00:00', 2408300, 'Nova Cruz/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-estrutural'), '<p>Atendimento de incêndio estrutural em Nova Cruz, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20251019-0095', '2025-10-19 10:35:00', 2411502, 'Santo Antônio/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'incendio-florestal'), '<p>Atendimento de incêndio florestal em Santo Antônio, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20251022-0096', '2025-10-22 11:10:00', 2413508, 'Serrinha/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'defesa-civil'), '<p>Atendimento de defesa civil em Serrinha, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4),
    ('OCR-20251026-0097', '2025-10-26 08:15:00', 2406205, 'Lagoa d''Anta/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'suporte-pre-hospitalar'), '<p>Atendimento de suporte pré-hospitalar em Lagoa d''Anta, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 1),
    ('OCR-20251029-0098', '2025-10-29 08:50:00', 2401701, 'Bom Jesus/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'outros'), '<p>Atendimento de outros em Bom Jesus, com equipes do 2º SGB realizando ações coordenadas.</p>', NULL, 'aberta', 2),
    ('OCR-20251101-0099', '2025-11-01 09:25:00', 2401206, 'Arês/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'busca-e-salvamento'), '<p>Atendimento de busca e salvamento em Arês, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 3),
    ('OCR-20251104-0100', '2025-11-04 10:00:00', 2403251, 'Parnamirim/RN', '2º SGB',
     (SELECT id FROM livro_ocorrencia_tipos WHERE slug = 'resgate-maritimo'), '<p>Atendimento de resgate marítimo em Parnamirim, com equipes do 2º SGB realizando ações coordenadas.</p>', '<p>Procedimentos concluídos com registro fotográfico e atualização no painel de ocorrências.</p>', 'concluida', 4);

    -- Ajusta a data de fechamento conforme o novo fluxo automatizado
    UPDATE livro_ocorrencias
    SET closed_at = DATE_ADD(data_ocorrencia, INTERVAL 3 HOUR)
    WHERE status = 'concluida';
